app:
    jwt:
        secret: ENC[AES256_GCM,data:l4vEKrqt0XakXP0UvYiUpvr2wvk7qnEw1v+3,iv:TMXRcf9K40srbdmmiskEs6TqVdxboybPyZlrGSXFNqQ=,tag:OWhUt0LS+fmDZ0TWDP/znw==,type:str]
        expirationInMs: ENC[AES256_GCM,data:GBQwCgMqUkwc1ZhHP1+i8pg=,iv:kBXajQxqsjPxkw8QrcJgZFH36wfpWdnSSGjclx1kIMw=,tag:pbBcmHHv55/oLDj1T3ow3Q==,type:int]
        refreshBeforeMs: ENC[AES256_GCM,data:nMaX0na46WF3X54FOxnUaw==,iv:oY+wf+J8YlgPqM/Tdye8x57FHBj0jEoQIf367kjzHjw=,tag:FzsxFyURtjaqzJQhuPp1Rw==,type:int]
api:
    imageKey: ENC[AES256_GCM,data:/NoU/B/HE2585CQyFLGXgPLh931E42fyTlxxjqrS6B7N,iv:YQaZeI16S044mwAhOoNhSgxUP01fVGslg3bWVFRSH/k=,tag:M6W0SkVLxIpBNmZhLOnRww==,type:str]
    tatoeba:
        sentences: ENC[AES256_GCM,data:/zXmOZa/PWgZLh2r8qNnU+UzPnGlvo9iOZ8mR0NLuXGWbZbcLUlQbGghxUEKwtcY7OIMcKeyRA==,iv:Wr40JBFd17SK3lBN9HlzM5n+78qA5HJv+WfdXyLyrRU=,tag:YzC8xCUMslg0HsxYY4IG5Q==,type:str]
        links: ENC[AES256_GCM,data:k4T0P5risY5L2/VJCpNP0OKGO5wL1nsotaxoUIxg3aiGizvEeCXLee01DaOhPcRpIzDY,iv:4Mq5ZtO+618skl6MKvqTOanyLDA9nSRd550AD1TlE1M=,tag:ppgG1y90VVzESgwlp1ES6w==,type:str]
logging:
    level:
        com.j0rsa: ENC[AES256_GCM,data:wxU7Aw==,iv:Rc7TxbgKLXJ3W8DlJpG2xClDZLGS3KaWyBRX2h/yUNg=,tag:E132gIS5NoVPYmz/OZAHjA==,type:str]
        org.springframework.core.env: ENC[AES256_GCM,data:cdM/ZQ==,iv:9ELFQKZ+POfWrcr/Hm0PJGpObCrYhoaCO3nGplmG1JM=,tag:VYI8cMlMXRHXLccgJwpCNw==,type:str]
sops:
    kms: []
    gcp_kms: []
    lastmodified: '2018-09-01T22:29:42Z'
    mac: ENC[AES256_GCM,data:tC/kSMnuB6+74acMPhJxg227fpCl+Byjgsd7ccUQDdSQ5Q9IF991f866RiDNaszdld/DZGKmGecvIl7ZEDdDxepxSj/2Su/WKxw8MAiXwZv2GtfJLI68pL5qz1N12mGv3NfunI9qXKu+hQkxWGlSmpYn2D+pXKh+gcY1oWTP4xQ=,iv:WiqzCQLxyRRVH9UQ67cOJT+N8lb0wfpQmHGuH84n/SY=,tag:8Yjt11ZAE+TLf2Ekz0UWBA==,type:str]
    pgp:
    -   created_at: '2018-09-01T22:29:41Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1vv+6TI6eoOAQ/+JunVbSp9NS/4dyVnFR7Wi3eDSfdDnvEA3HLpVc08R+9a
            Ro0lRRE1c3cxpk+58GZLv+0NBCYTREODtln8eAQPrkYlaFa2maN5aqbwuXkWit5d
            0hlvriNsWd0mTPHM6A69i0HM3FwqrnbmzWcpNUI1a0+Cj5D8OEo9z8SL/nYTNDo6
            Xj/pVXeB6P7XZkvKoiRNSGYN15Q6vkMBl7wpdUfx0S4ciz2ewrYTyNFspDsSWLK9
            PAfMlxs0Mrf2lq/43pZLrY/eEY3O6TbL3/6VGY+izRj10F8rBzYVcz3mkNDkWSiH
            B0f8ivNxstQWLkiPSqBTl5/h+3/a1UhqLK9ynSFLguFews2kXsMSBt/CeqeG8nbt
            zhZMYoilYr6v1RNBb2p1jkDNGZg0NOwQ6WSrgwOfZfZQvBiyvOy4C5bdPqtb+SJW
            VvrKYGqbuk1UlOo92bN7KCIBnwD4//Yrwnvpc9uIThOvQEzeMa37oXyOqW0mxDZF
            vgVLqvIMIxM/os47y5TBI9af4stoJoJqf7T2wIzJEny8TbNW1bX6O60jPIJp4Wdz
            3dwPew90CigVzcYXk1zbilY1qnWRD/1oZYVz3g0Ohpqfy0tlK+WIGqNCtGOu7hB7
            W6sFOqBCIOVl1Svv+8C3OE3NCJUUig7MOBHWCxgT4Itd/eXGC4Tto5vgLDPTfIDS
            XgGMRlLhuqHvy8PHw3ykSltD8h4Dm1wtnWGnyusAzYedpcbi8yvhxohSlXXEwtuZ
            2XljWaaEmozmGqiCXIN/qjlgfX7YkyhLaGVMQamVX1l9LZL3X7YPPkP3ngAncRQ=
            =wrK8
            -----END PGP MESSAGE-----
        fp: DEB65D13130FF2054E4EA1D3BAF76C7DCFCE45E4
    -   created_at: '2018-09-01T22:29:41Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA30Lo5zeEXnQAQ//cGhTDDh03Nrf7Y72aF2yxzzp/hduexfNfBsvjzZGZTFN
            qWNjxM2bDwNzK4vgcOcEu/jU8BJ7GZ/XRF+mCJ/m6XwCbYusQVIIo4OKbu3yrhHr
            Ppa4IFXLegWBACxx1OYb71d1n1WSNPe0M7xWWpCJ61JtW+nsemNFTo9fASjD9cs+
            fzBQI0E3jx+aplbYKW8pzurILrv0Qn8c5Z/6hfmMLsYykZarDvb254TJvM8nNtgW
            D8h8pOqOTMFIn+OMX0haOYVx9p/18Cj4NYmw9j3J5kmgEHIdXLrkDMhefNVOS3fA
            cMV/Vm/4kcXLOeYRLtnq1elPSU5Qt0/KamilTY9r2eZ1kInsisqEovaMuVEuBZg2
            A4y9XoYtF1g+tx4iKJ0KwHTe6SgBKm0bLZJdrFTorgD+QZ0B48vp5kZE91IMCYIw
            53PM+u873lw6q9JII4tweIjEzppW5ULF1vDxCPdeWFRvg4q8tStqgdbQulpvDKKx
            Z+BdR6AvPHVFG3zvWHbj9o8sfIeZx07itcU8P/uEC0P5GEB6G29K8JMGmzOnR0Cm
            17sxEdWbBKQ4vRC7rXF6Ugv9cHDpNF19jmleNUz7JbUDat5bRAsxNm8f/yBAK4pU
            YYG1dv6yQb12FqE3llPhHCJKFN7f0xdYrdsEc5RN3Vn++OvUyaBcMJHHPYWSSz/S
            XgGIIifM7ngGqHgLT4364k2mFrLeMsvlrByDOs1qC4PKI8A1o5QScTOMGDF+FubX
            B2h0LuFgcT680qX7FYlw2qlAtmVlhzqv76zc6rfyeXqv4zwgqgD4bc+UiZbC9F8=
            =cERm
            -----END PGP MESSAGE-----
        fp: D44E294BEBB7756DCDB318C44ED57D2604450939
    -   created_at: '2018-09-01T22:29:41Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyNgEE/PcVg8AQ//VypKwwLKgOQ1tiBIWnDoAJhundKY7JobyIsNInSdLSbI
            oxd5+1Pb5p36e9LccloxvKWTcDna0BOuwKJ1zz7r7hSfqXhuEhGgE/NrdQ04zdIp
            EF8lPYnxJRql5rqLgpw3/KX7wmwi6F7TpqEMuQs/5nFgt5+GXOySClDN1cI97Mkw
            HbIl4HI7kCxJfO1OPl3+I3sGNQ9zuNTQ3JvES7YAvvxuDPM5M9TDYIhSWa8fTiCX
            fOQy5qqHaVytLKMzls/muyVG2EINPqgzbVmQfgBVX+RJEBi4xfKBpTjhG6TmHxFk
            oEENuLk7/rGe+cD3J7k9cMRbh70SDx3X82IDexuYPaArUv1BUAk86121SP6L+0g/
            YsE5f6dqL/70UfhVNgDXuUdwaTETJpnGVvlgLYMx+MKaSFyI9QuqFZ2nkx8ATI+w
            k2eE4NNHBzgSFotFgzZgxHbhwAjOJDluoAotULsMS548gv4HF3Fnt8JWJrPm1nvh
            W0saofHOTeJ78YWsDYAde3UVBB2WFU0gtH3kLZcHpWju9UGZucLXGIDCSRB+/Wa5
            l2173Cj+pLXXxoMAr3fRwTA/TPUihTmwrYVaFTepHuIsDHjPR6w3FLB6Vm/8+Iji
            c1pjyf5rce8yz1W6egfQ+d0OQXwNHm2Cz4wOxQvJU12+/e+fOlzirj/LgT4zPwDS
            XgFd/j/yM3wZ0/XfGEdIkn5fljmgrm6TlNlzXKRHk1eSnMPmECnwa36yW4Rnx5cZ
            tLNkfWjhpo4puslKoo0XWkKmYmb/jtYPd2lKtSAbC7xn9Hx2fBcfw4Pnl9/e658=
            =6OO8
            -----END PGP MESSAGE-----
        fp: 410C14551CD6E201636107DF7C9728CE5A3FE9EF
    unencrypted_suffix: _unencrypted
    version: 3.0.5
