app:
    jwt:
        secret: ENC[AES256_GCM,data:VPgZvlr/ipiAdRgejv3S/f/9p9ifPkfHbIUR,iv:WLyVwLVXUavRsJ1zoZuKNiToDcXu0VuAu+JhZWgDkqM=,tag:dzxWKVfXs/KnMTaPvHz03w==,type:str]
        expirationInMs: ENC[AES256_GCM,data:6SbSsl1S++072gipcRLj2tE=,iv:eXhTL+qKz3Il/ZGpUPR7vKUrZH5rL+XUwssJqaj8ibA=,tag:HrC0G7jS3jcjI6cJCnP0Vw==,type:int]
        refreshBeforeMs: ENC[AES256_GCM,data:U4QzQxudXqu6OktEgTZyLw==,iv:XMxNmU2IEixrFHaNSTKG2BSZnH67s1mB/B8yUCBY2js=,tag:qeJNDDU5kd1/3NFXwzkTGA==,type:int]
logging:
    level:
        com.j0rsa: ENC[AES256_GCM,data:+P506A==,iv:M2AAz5yVqDBJWHZ37vRRHhwzO78ro3O3647Lve9mCxA=,tag:bRVdAEAEuPS87iEjiwneVA==,type:str]
        org.springframework.core.env: ENC[AES256_GCM,data:PFcKKg==,iv:7luXG5EZsDDueifAdiefXTGcNd7/LMyZefcQbZU5IM4=,tag:fdH8lFjIcEXkQwYIkJP/yQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    lastmodified: '2018-06-30T12:48:03Z'
    mac: ENC[AES256_GCM,data:YZRRQY7BiEdUo0TbruUfE8XazHlbxtGNb4VXH829kVMPoQbIYCaK45dl7MwsjKsn40JJtN8h95D2y1nja3AU3x+942nknMo3XfFY50lyWkb+5AvNXQWFfU8Lk8rHUi/Z3SCWU5VuDX1Iv+KX2KVIVshF09h6c+zY2kT11fQh8j8=,iv:7zb4dIqeSq+U0vi6xIGu/1xC4uN0mcTpvd91WEg8mqU=,tag:KgjWaQPEUsKhcO2/cT7tXg==,type:str]
    pgp:
    -   created_at: '2018-06-30T12:48:01Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1vv+6TI6eoOARAAjzeijRuIyMyKLcYi4gFYEt2ig6FeMAw5XklpESNTAoH8
            QpZpI6ljAzYWWDcV4w1GLZJZC60jkMd9P4SvYXHhWupyLR+kD58KsM+J0BDcovUg
            8egMMeElo33C/nyK6ZdczwgzByfzlLznHx9Z102HlhzW2hmxdPdgZLB5w91YVxss
            yJ/KrO0TScFTOzKpn4O9Xp0ZN2Zezr30LkjDEu1NHCM2Pp9TztNrq/ZZxEvlTxWR
            Tg+WImAssPJaqq8ea5PHR/toPs429lCHNVFrhMPemUxMF8uGBrndO6vbmWH+cq7x
            AqIo1u7nHCgfYk1sof89mxjy3D8S7WCfOWqtf5iruv0HPWVveF7QG6mBOUdT4Rl+
            07xUKM+KKaNlN8vFAmva1ZY+f5tGyOmx2P4cKOZkhpSkqcIAkO5ug2s8BszBfzJa
            oGwQfL+YdQSl73MZE9sfccuSt7rVs5+24Pgetl4wU0+rXbb2Qar5kzHI/Zn/TLL1
            lMbN4leoAptIbcqfpeI/IZfeCSvUQaMfZnmNfr3SOE6AUq1G/v8k9c84Rmsjbkap
            TYb5tl+oXgN0ACI7R+vjaDJlbjFFVir6tHW4/TkgyxbRBZ/pBVc7Csl6ONYeMCbT
            47edZ7BFbToGbC2JlfLIfrIKlNA95r2VUJht6GkR45bCJWUxkl5iQPCWY2+pTz3S
            XAEy0XNAgVqtlbsGk9xoNlBug7qPtnqKVkmvESiySmy2WYRy4tusm667FV3LEK9O
            gLDst5UNt2Fgbqakb5aBYb6MwoNZAHPpMFyfD8lA+w8JMqwMNjlr2eSG7dqs
            =yCPM
            -----END PGP MESSAGE-----
        fp: DEB65D13130FF2054E4EA1D3BAF76C7DCFCE45E4
    -   created_at: '2018-06-30T12:48:01Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA30Lo5zeEXnQAQ/+OUdu6MmmFiqoGujmScrEQXwebQ1y58kdtPxnoXg6f4vD
            RIpXVCYXAEFJpAOC1eaW8yUWFKGqoY52mX0oUk3lKiq2ASr8v9PVoCntbM7o4u5A
            zc+thHf6BrnMfdG1Hql086u0cGQyyUKLQBHhXT08TkabERnkAj+Ji/9GSpbhhD1C
            ZdQsa6g8k4YAhCQIaoRDZwbktkdTn/jPnaXby9e7MxB127pQ2/PoxXzgCipNJxia
            oYmDbFO/BrXcFacRfo5aB7mRL3OBJWjXEmn4C0oRvzbCP9HP65psl01wenl2TuAs
            uJCd+5mMPThHNznORqLfVJa/DOMPTf879g3YjVBQC3oe9asxPWyfZCgVb+rFNq5m
            mHpBL5c/2zehZYu8SqP9xT23zue6ctZweoEJs80DVbw/2WehRavEf7Piozvc+DxL
            rozG72PDTd1VYawr9tvUSjh0HXWI+e+TbwryTzbUBGwwYsKxK2gGsqIbP8hRiz14
            EQn5aRnlXCZvOlwBJAHZDnCdkCaaO4yDvzn8fYsAT/uk5+geqwAFOByMUI+9ymP4
            NjkKCJquYiUgKtquFnAhUs52e/03r461n0SwTil7/umaBHAexTtLc1JWOFy7HQTu
            cA51smdXM/3RybnDBKRiaW2gZX06wyRFLzTi0vqEeNFL4kocWnEGK0cxLgdCsbrS
            XAFSiRtY/ymPLzRv2nRUG36Sj7MfU45Gq9XDUeGT6HuCCX8D1863JFx/QvuVNe3G
            2u+M4GFvidWL21TjXSeiz3exicmTJrC+HT2DZksEFWI9RIJyUXBEVBYFNSqY
            =W4OL
            -----END PGP MESSAGE-----
        fp: D44E294BEBB7756DCDB318C44ED57D2604450939
    -   created_at: '2018-06-30T12:48:01Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyNgEE/PcVg8ARAAvKt+Nb+oKLQItgDEXTq5dctipkqppGRy68z3GO299ITy
            kF7kVntTHJalnyNR1bQl4g8tUyNI9tlGl10AqRecvhMRIrtM1+RtrXX+LkRWTI4n
            Ag0Ty4ty4gK2+2+r/441fjlxRm3v1vTyzg505k883PmGBipY6Q9cqyDRa+FKFNPM
            T4/eU3viGuG59+oQb5jg2agxbkG3NKyL3/wFU9lo7WIyKemOjSkH5M3BU2V1qC8d
            yiW3UfOVJqhgtHaf6k3Fqml7+/xgUhDMfotL8Q64N0tcrmqKQOHo8r1GEVmW3lD6
            14SGJxGBQTwEAonJw3XMOv4IHcH/dqRIsiZAochan6aUHvkHbvkMzqJWAUjlSVIG
            QlSNRJNIVYeB5g6w+ErlsGiE5aG9k49KkrYd5SPA37Vb2Jym7bmLtwfKMRzlqseO
            zb0mqiy/wJp0H26QF4abT1FrU0CDQgn8N7yrbQuDzix4Y5OtbKCwxy6P9x+OyHg1
            fMwvK0CkBkqFE2TvuefB7AnE0+cDSz+y9DXj4cAPxAUptVfQoxGBAgfreQq4GI/p
            nEvwOT0S2Ts7CKTOVQwBKdUwrKgAkPzTe6dK/9mspC08yWSt74yGqcKUysNYfDw9
            1xdnQgsfMQgK5akoQ8kUToVLjN2Iw1ULWE1FHNldeDiu9u5TkqBSf0XBK/SMCznS
            XAGf9YWO8A84TN/Or764i2AHlS5bNCkg1cgFuLa0YbaPv0QZ2L7IN9gCijPm2r2D
            ZlwpeMWEA33iQrnO1lrx8eR47u5bL5aLRnNIMVKilVx/+OSr53jZjB+Pt5He
            =h/CO
            -----END PGP MESSAGE-----
        fp: 410C14551CD6E201636107DF7C9728CE5A3FE9EF
    unencrypted_suffix: _unencrypted
    version: 3.0.5
