app:
    jwt:
        secret: ENC[AES256_GCM,data:vVYOT2vnpZtRQgSWUz8hpnNA844KHjefC1cy,iv:DnpPn0dzM269EWzVbNv8Bz7QjZVzpOZGmb6eLbJdEZA=,tag:7ZaoQUiFmr02RszD5m2DNA==,type:str]
        expirationInMs: ENC[AES256_GCM,data:+mxAGzNP1byjbFGMBCjDyso=,iv:KYGoPccr6mTx0SG3toXxiYL7x67HfHF94x2POqvClnY=,tag:rtxXyzDjR45hFWsuDGVjcg==,type:int]
        refreshBeforeMs: ENC[AES256_GCM,data:O+KOhN6Z536ZnEnMqodw+A==,iv:v9v7ytmD9EHT/p/Fd4EUrWnE8QPdSTHowAKBwINvKzo=,tag:jRPjaR1VasQcNNJUt5Kq1Q==,type:int]
sops:
    kms: []
    gcp_kms: []
    lastmodified: '2018-06-29T19:14:16Z'
    mac: ENC[AES256_GCM,data:2HUy5fBCVNW8s2dMk5ygJif3SVbQ9vrtpjEXc6zjY9Mq/ApFas9uyzKAu1TbYxD0M7ytn8/vxrdHG8kLzj+OpJ0crmgNGG4sH0Rmrxdt/i9aIVJuK7MUDGeQkKPpnApqD9cYY7/fchVnhDyDEbnGyEBmFeLOa8SAAhOGJlB6X7c=,iv:dOn5U5mdAAB7+S2v1VcLbLUEkD3ai8FmoseI+a3wAMI=,tag:sTX+OhPu/L9WfiOsi3puKw==,type:str]
    pgp:
    -   created_at: '2018-06-29T19:14:15Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1vv+6TI6eoOAQ//ZZmC4eF1wB9GgcoCzBjvMsSo+SEw5kr93KOvmkht73HJ
            AMxOVWjgAJ0N8wRr6s27ZcnekrIU+IhOVLWbzumEGhcYjJUccPaUM82/EjN6cPL+
            ooboFG/noiwTgeY64nEeI54sLFu7QHJfEhcVp3xHPhCiYWj4qxrNSs27XlAYWT5u
            yEP+W/GSwt9TIGy9VJgRi/qFZjOvOqdWLS/h0KvEa3SCTVGCO9yGVhkWVnAqHxla
            oSWqqvVdyZi271ohkDjULgMwiF74Ufgrozc2yvzGq/o9b+16ylA9iNRGZlN/l0TX
            IW479cVMJ2OGan0kaxIp/cN94rVlNYWzvy+DZJALz89MMF8H0XdlMAjkjd/MinyG
            dr02SaUDD2yKkG3GiUeCcdPwweU51mwFnXf33D6eU//lhGo+PIxaA+ttFeGZUjCe
            CyWLiQneywd+h5GyObzGgKNNpgbEJ4T/VXcsOZYhGwpnniR4ZwY5B1722y6Iyqx+
            M3Vlx5221p9ixgE3CpDYN/1pFPWlKMqFKS9ETh8RLoykwyVhqUZkRxWQLEUog/y7
            POZqGPiRcUsljO98oqQBTOGQRByRSx5kJcHH8leeXFcjElSMvQ3uMHBujUe42RK+
            M4JOvVIxfgL4UO55lLz84ZqXCgDQmL6OjzK31+GpNrqD8tW2/GGEsPrgdo6KcbjS
            XgHp13dgqykICo8DUdm7unQM//cGIQRU+LwE/J39PamBcEYzJE++BGoQuAmxT7RW
            6b9f7ZJhxaQHnVF39fI9zFqhR1V9ky/IfF5apferlT3zn7JNmnGAfMr/9LtGrZk=
            =Q6BV
            -----END PGP MESSAGE-----
        fp: DEB65D13130FF2054E4EA1D3BAF76C7DCFCE45E4
    -   created_at: '2018-06-29T19:14:15Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA30Lo5zeEXnQAQ/8D2tELXxBs6ca/11l20BOcW/MXi83/tnZVBeyaWCTaCf5
            o2Bz1iuacWA/r7sEBNUXB1f7IOj6SaAD9numcoJAtQXMrrYcc1Nz+FMgRBYM3/l3
            IP/SF+uU5xkVONYbmHjGsgpBzfauCz/2WDUIM0yKEwXYNOzf/qbZYMU9zZk9ng/c
            Gi3eAcpOJEG69SR6efgupATiO55Krg4N/Bk3w7FKbbiWXHGaFozobmZB0w2obQdb
            /kR5eKkSD1hXWNqXWiuG4ESo4UukDlGGEycCXGNKvTZDus5V/N61PPQcfm5jn2TW
            pLPwy7O5gYAcsjSURYEguDE+TRXXKVF5zGL/HIdGy9SlttYdX0xUIMWFiYrNXhN0
            50hwsc7io8/Rpj8wcDZPz94r2pya4L+weHRgjQn5vCt0eeB9OyOw2L2XJCD6inqq
            TB4EAppadnzU/fgQQD6JI/silUbe8PNG3Gu/DddccCLYkzcCPsfJjYvawcKcGSrE
            KzG970WSx9ARIG3rtrJBtJ7kf/OyMv1zUleGrv3EfoQN7Re9mQ6n3U033diG2jX0
            vzzf/BqQJ8/+tcjgK7DHBdLerqVu6c78K1wXNI1y/9Si4L3jpN/3mHq6aJEXKN2q
            KHRKkQj7xpv1Wsh8cWkQ5oZvntG9qa4Veu9npTwInoRNYhzBzWW9o/UWXklWgyvS
            XgHpvHVfR7loTvx05ItsfEE/qWbqyTBVjzsFuMsyLmLv6uk2iAm6eOkPESwPGZnN
            rkY7ZuqQCNfvGZPnTbBGqGumRQaI5cL+RAJ0wbU01yq68rvyzK5rXDuLEEyoPY0=
            =vP14
            -----END PGP MESSAGE-----
        fp: D44E294BEBB7756DCDB318C44ED57D2604450939
    -   created_at: '2018-06-29T19:14:15Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0QVFEwfeFZhARAAk7WbVpE08msQqokYtD9rE6XIOFT68GUSn9GUBk4d1Lqy
            /N3a0aQy8KdomiuhfWpyNp3eI64lTD6827PW2rU/581scwR8inwbKMsgiYOiaChS
            +f8DhLOMlbm+yJ/3tH8ZYwFksfxUbyJJoYn+mrv9WcAPTYawCmbh16OMFlSWhKQj
            lxz86oc8WTAGS1LZVG/L5BjOyyIHYiNT+ZkVdHohwhcNEv+CmlMyLwRa0dVlpMkh
            9EBynTb5FG0D33vGPZVpHK1RB3nVVnRXh7nyhs1I2wAlKMkEsFIJbxk0lZKpq3Gl
            x8Lyr36vpBS+ziwH/RwU7eLKOpdHAmjuqokm/BGZxvzuygFF7l569pnsLn6uhGpZ
            /ONrrK81fZpUfrutpU70FLFMTO2OC0fcthTalHh7lKfdHuNmc70Un+djPIhPlDK1
            pooZrdo3+ObZtJjfSonw/IzfkWGDw7oQuVcHmjV+61nWpicTjJUFLoTGLIkh5Uly
            IBk+TZfGGQeU9yYjLO0VHJZJepn2hoEawMukixdrEmL9QCk/2RU/uL2CNMZCOiEH
            3C/WaXebMaokHlyRih4Tm04zXJjFSqpZreT2CRWPQKy1sIRq4s8R9TSfOB2zdUb9
            8l1cLcfm6P4lkdYpa0rwDWOjvmh5jp0l0XLWXak+AUPjk1h551HgDg8qwxiNszvS
            XgGvZu7ymOJ2/OW0Cg0cp3yhbmSNgz5vdmIGPhG18Lzr0U0nkpIOuW40MAelGfPg
            bJ9a+XU96fN6FUti8MpPcr4BxkcTrwpPcfiCdccUNqOgvVWygxKt3fAng7bucv4=
            =zGbK
            -----END PGP MESSAGE-----
        fp: A78E3237C4D6A50E22C021C09DAEAA377BF1073B
    unencrypted_suffix: _unencrypted
    version: 3.0.5
