app:
    jwt:
        secret: ENC[AES256_GCM,data:DMuPz8ok9nigxVP9q0ahkQpI7000e34aCibL,iv:wFT6I3PNHvptvTWaMMAjfzSW/++s7k2mt14k0NNADvA=,tag:V+L987i1Ce4x86t1rTXaEg==,type:str]
        expirationInMs: ENC[AES256_GCM,data:xIjQz59z+x/xUtPhNJhV8Zg=,iv:i6usLnJMt4bPELj+F7ZWLRd5HraUaArUNx5ElKtQ0lM=,tag:aJwcSHFetjLBFRSRSwHlCQ==,type:int]
        refreshBeforeMs: ENC[AES256_GCM,data:aVSfqbdzHM97Qu1r/B1aWw==,iv:tBgxR+0ZX9lnTAo0Z75ky31Dkv02uHLKDy5KbkyUATk=,tag:tDVmVligKkViDfEaxNd3/g==,type:int]
api:
    imageKey: ENC[AES256_GCM,data:eerSQfluB6gGeCtaLcVGbomD91Sj8fRdW047Fzsffqnq,iv:/xKfbo2g28yvO+yaSIGm3kFBBN6yywBXebJNuhRKs1g=,tag:WAayx5cX1G94P4npY9+KMw==,type:str]
    tatoeba:
        sentences: ENC[AES256_GCM,data:ofbhaME7EKQqKiksaszmEukEd9VOdLn56I0q/rqcsyimGu2gDbvVaisggYmJvzF51XKcYQm2Fw==,iv:lHReOvPyodxI1jbX78QF2FCNpTCJBtQHt+DNs39pw+k=,tag:4z3T4/V1z2g+vcZkX7XY1g==,type:str]
        links: ENC[AES256_GCM,data:kMgxui3/7az2wFZf3iu/vjF8rE/zuGJ2ukqNgAoEEcVJf0958SiZljoQmN4AetdHLxZn,iv:MZlOu18Vpe7z2A88slH2kk+uBFuiOb/WfZWvtnL+XkU=,tag:BjMWOBF81guWcLiEpSAcPw==,type:str]
logging:
    level:
        com.j0rsa: ENC[AES256_GCM,data:5IZM0g==,iv:XeQd5um7F4fho+XRP0xXbdUzfbY/Ze24d1uP2sNaEHQ=,tag:vAccjX81Fd1ugTRskd8ZSQ==,type:str]
        org.springframework.core.env: ENC[AES256_GCM,data:scpvRQ==,iv:NRzoaNfwd+ACXG8eg7bk8ZBgcbfu5c+8NLPCSVlp+mM=,tag:YddN8oxr0fpm7Bi8GLvfog==,type:str]
spring.data.mongodb:
    uri: ENC[AES256_GCM,data:wYvPjgGxJFu5o9NmX1BF5trrhc9+7znnMIVtYN/mtyL3acSePGChg9SVwCl4yUWThOrlXKrqCKOhtMKptTH3BPf7PenilVw=,iv:Ahko702+3GoD90OA/cUTUESTO0TaLFQf88tOzBmAKzI=,tag:tzaRM1XJ25bNGsC1CtbvEQ==,type:str]
    #ENC[AES256_GCM,data:M7WDyvSgS69hLh94EecnTg45ZE4t8t/eDtpG2bNioxPjnOFToN0zkxUI1URnmvRnAh61MPyteTBpGgcfbqb/0nRCfg==,iv:Q/m+uQUfQr7bHcRR7OZnjm+x4bHvmipA1y+E02Dz6AI=,tag:7LcbzCONDPFW2BtpvJYF7Q==,type:comment]
sops:
    kms: []
    gcp_kms: []
    lastmodified: '2018-09-02T13:24:13Z'
    mac: ENC[AES256_GCM,data:KLo3B00RZvMRkeeTSM+wUSdDK4j/bGydgGY/A+1JXgtpoUpbVX7j+0B8Ab84/JqgFRmDKN+mZE47ZSnZdIirrBCKyao3ccn7kCfHqkAfpY045KYEsW64OriGfaZapT1RTsjen9vLYzKxaJi0CGq61nG4g1PpY3C2gI4crgAzykg=,iv:bjsmCIOU6FoExgXXeclDkdJxQ19mLPvWa6IotTB5bsY=,tag:Ec59JQULcElfO7haFyl7bA==,type:str]
    pgp:
    -   created_at: '2018-09-02T13:24:12Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1vv+6TI6eoOAQ//W3tSMJRqkpIJhn5RO2iiPiqsCOAdgsCh2ZW0yp+ybOAW
            xlSIJEgxvWr42gQijQB2O4Ohw6j0INNLVGraWgiBxlnyy39i8skIF1tAAqIgiAgx
            gz22hHlZIMKxPNdwqvJLuPPorqeZj8Tjwh+e/0LIwYiJcyL44v+1wc4vTOscsW13
            64x86tlTQqlcRmtMu3IfGibmQi/DWz+bCIYrjd6fKomoNgkJzLKNubA7j15DzEAe
            PPt292zFRtWD2PMGvKfH9eg9g6B3vgu2XM4PjZmeyQc3UwgLe6nvd6X8tvjVSEhS
            MwTTA7tp0jvBFJwWD6mnxlJhV48nP1hkJKS2ssWtkWpohKVRq8YrMZkXUb70q9pD
            5I++8uVdyYzj5bBXwBbnSq8vfYddh4h0Kz3qRimqkbogSFgeRMJjaLwIazZtlMaA
            PebATEUR21wFJB93aYa6C6rkSyp4+cocOVMQPHLsaoTK5eGllyTqUwQRpLniJhMz
            QGtl8dYBb/f5eEg3FXZtqEp4xqvr7MiZ7Wy2jcdCE7JK4vMghKJMQwDiImhudMyR
            V4WSXaC0Gryms1D/xu5mfY3BDlQLp5vvfP6HcqO77Q0fqeFznyh0mxlG7DvVfiK8
            OULe7GHIk/j4kK29HxTCcblJ5ZqJwcWQRWjDmGO5pp5KUXuxzFS1jzM4WhgUDlrS
            XAGiusklIKJEZ/cYUDA0ECoMin94hRFkvbGi+jXbOSYA9kvba75s7wOcApy8+tyS
            Dj/HIkBj3ltJ8HZeRSYKTNMu0WtjN97+fxSUZeCuj1/g0XJdjI2AUO7y7lP5
            =9Qur
            -----END PGP MESSAGE-----
        fp: DEB65D13130FF2054E4EA1D3BAF76C7DCFCE45E4
    -   created_at: '2018-09-02T13:24:12Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA30Lo5zeEXnQAQ/8DkeQEQagHBpc0G0SRc7Bu0wmeeuWpw19ev9fZvWIaIdb
            LQUiUkrqDOb6jasj1DSyGiB4vZma87E7wgUJzfHzN2LWq1Y3aB12UQ6GjpMumWOC
            P5Y1CrLUxxMkn1ifDvegh1/zmEnjW1UqHyqJL1lXNrf9pdLC/TggatAIXtvS+h1D
            yuw0ck7SZOaeQsZeTmQkQ/LKZZzyiuYGsnnSs47UZVvVSbSjt3nQ8sVcEof7KAKP
            vNygpOsNfISxsmpbpTxH1k7B+LdQJX1NcJOpTrGuFe/Xkf3sTduAW4j377GQYeG9
            Ld+NCyBG5j7BFKezYERQ6bGLZhRP+pA9Dp/hztjlYfXDJvHRURUYjI7zteStqvuQ
            huEUWWvfGxgJhXd2gQLfNaCiDDTdjjk4xcy1kA2TOqKF+yfyWU7GMDMeXNorNMWr
            Z1vN5joMhMQ6izVn7ylFWHpgnzR0Bowy3t0qet+FwSlMLj4cxJOS5EO5ZGhX21aj
            WhBkrWD3g31qL7k00XBKEn+jSf7AjL8Rne5PKxdLeOnwJBNymUSXkxtfdY/7WKkY
            4Qq/QaRzXZsoMbBB7ZGbSZrgoqYjXrD7dOLJ85fx2/PYs0lDogiFszw2xbpzmlw+
            xa1pHsgqiIEXCqo/6YqHhrYc5LdoGNeZMFNkZIDgZ8bZWn/55jRddcRx7gLuFqDS
            XAGSEtMhJfxZJk6SPeZmrfNfndTZUzwLxd+3XprD1KlQngEy9cKXSQIlej8zgxg0
            3R1ITpb1KtEAryw64X5SrjsP65LwobvE2KhbCzQiRLvlEYCWXACrQORX7l8f
            =6qdJ
            -----END PGP MESSAGE-----
        fp: D44E294BEBB7756DCDB318C44ED57D2604450939
    -   created_at: '2018-09-02T13:24:12Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyNgEE/PcVg8ARAAkPG8lZvN+NCXW9priSY0sauhDTqFwbgJtmnXnHPVOlT4
            nJvI8LiT2L67fknorl9KZoPy0FXx6SfrDTQDZCGl77C+vSLNN+tECwk5zedoe4Lc
            g4L+AxYVHpXj/eYUi4uNOuQhzoksMY9OdeBPakzSiHpJZRD/FovGk+y2IlB26DAR
            eVJTw/ZTvnBTQ/HZ762UvtUO24oBa5Pnvtn0+0ZoY5uRr0tgSHRUuC440tL1KU7H
            XrdVYgFOFOCRlMsRO8l95tCuIVLcmqTfL6xwc/kcscDgyPiCBEvZOWZVMcCj3h4L
            gWwfIQHgnY1F2WjZ2yI0nhcmRAzBqTILTv/xhN3HZn6z78ir+35GpadNBh3CGbto
            tZN+J82k4R2VMMxrVgZ8waAWle9LZmPiVJ1uqwG0rqLCiybpoAFKVjHUvbGycJFM
            XRUmcaZlIhI+YGoot97aA6IbBUO0Qthl0jeboUZb6Vz75r29lZcIIstUGQS4z7YO
            bZUxMhHYhX63j67abYYUpTAmE6a0VdWO795KV1+Od8/GsCIBQTZ6LXDK16uAMFYA
            I60SdMEOVxYc3ka/lFiFUO24wHD10fVLoc2Ymx6H8ykXumiWoFijiYoIckxyt0t9
            w+K0v2FDUX5aOCyC/VwEQXpZQKF3vA3gVVE5b/9VmgRj6UosIYjZ2+4l/yJOIz7S
            XAHU6EvOf2IHAdGkuKHqquuplO9+ZaePoht98ahuyBS2RHGVNSMnllljpgQuruuE
            TRyFW/wVx837LZ5KcUuGIoSXEzljsPjmNNsko5bPtmQqWD8qR7xD9xhIl1a2
            =qbv5
            -----END PGP MESSAGE-----
        fp: 410C14551CD6E201636107DF7C9728CE5A3FE9EF
    unencrypted_suffix: _unencrypted
    version: 3.0.5
